/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./components/common/AuthLayout.vue')['default']
    HistoryDialog: typeof import('./components/chat/HistoryDialog.vue')['default']
    MainLayout: typeof import('./components/common/MainLayout.vue')['default']
    MenuComponent: typeof import('./components/common/MenuComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
